# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lift_gui.ui'
#
# Created: Wed Oct 26 20:39:22 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 751, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 281, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lcdNumber = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 281, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 281, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.horizontalLayoutWidget_3)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.horizontalLayout_3.addWidget(self.lcdNumber_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.line_3 = QtGui.QFrame(self.groupBox_3)
        self.line_3.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 180, 281, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.horizontalLayoutWidget_4)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.horizontalLayout_4.addWidget(self.lcdNumber_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.pushButton_7 = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.line_4 = QtGui.QFrame(self.groupBox_4)
        self.line_4.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 340, 281, 141))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.horizontalLayoutWidget_5)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.horizontalLayout_5.addWidget(self.lcdNumber_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.pushButton_9 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.line_5 = QtGui.QFrame(self.groupBox_5)
        self.line_5.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(380, 30, 281, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.horizontalLayoutWidget_6)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.horizontalLayout_6.addWidget(self.lcdNumber_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.pushButton_11 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.line_6 = QtGui.QFrame(self.groupBox_6)
        self.line_6.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(380, 190, 281, 141))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.horizontalLayoutWidget_7)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.horizontalLayout_7.addWidget(self.lcdNumber_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.pushButton_13 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_7.addWidget(self.pushButton_13)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.line_7 = QtGui.QFrame(self.groupBox_7)
        self.line_7.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(380, 350, 281, 141))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 30, 241, 30))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lcdNumber_8 = QtGui.QLCDNumber(self.horizontalLayoutWidget_8)
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.horizontalLayout_8.addWidget(self.lcdNumber_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.pushButton_15 = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_8.addWidget(self.pushButton_15)
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.line_8 = QtGui.QFrame(self.groupBox_8)
        self.line_8.setGeometry(QtCore.QRect(20, 70, 241, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuMenu.addAction(self.actionClose)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "System Status", None))
        self.groupBox.setTitle(_translate("MainWindow", "x_axis", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "y_axis", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Donor ctrl", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "x_axis | stepper", None))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "y_axis | stepper", None))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "z_axis | stepper", None))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "x_axis | piezo", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "y_axis | piezo", None))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "z_axis | piezo", None))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Receiver ctrl", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Laser ctrl", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Scripts", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

