# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LIFT_GUI.ui'
#
# Created: Tue Apr 04 10:41:59 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 593)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_general = QtGui.QWidget()
        self.tab_general.setObjectName(_fromUtf8("tab_general"))
        self.groupBox = QtGui.QGroupBox(self.tab_general)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 751, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(30, 30, 579, 119))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_zstage_ctrl = QtGui.QLabel(self.widget)
        self.label_zstage_ctrl.setObjectName(_fromUtf8("label_zstage_ctrl"))
        self.verticalLayout.addWidget(self.label_zstage_ctrl)
        self.lineEdit_zstage_ctrl_status = QtGui.QLineEdit(self.widget)
        self.lineEdit_zstage_ctrl_status.setEnabled(False)
        self.lineEdit_zstage_ctrl_status.setFrame(True)
        self.lineEdit_zstage_ctrl_status.setReadOnly(True)
        self.lineEdit_zstage_ctrl_status.setObjectName(_fromUtf8("lineEdit_zstage_ctrl_status"))
        self.verticalLayout.addWidget(self.lineEdit_zstage_ctrl_status)
        self.pushButton_zstage_ctrl_start = QtGui.QPushButton(self.widget)
        self.pushButton_zstage_ctrl_start.setObjectName(_fromUtf8("pushButton_zstage_ctrl_start"))
        self.verticalLayout.addWidget(self.pushButton_zstage_ctrl_start)
        self.pushButton_zstage_ctrl_stop = QtGui.QPushButton(self.widget)
        self.pushButton_zstage_ctrl_stop.setObjectName(_fromUtf8("pushButton_zstage_ctrl_stop"))
        self.verticalLayout.addWidget(self.pushButton_zstage_ctrl_stop)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_donor_ctrl = QtGui.QLabel(self.widget)
        self.label_donor_ctrl.setObjectName(_fromUtf8("label_donor_ctrl"))
        self.verticalLayout_2.addWidget(self.label_donor_ctrl)
        self.lineEdit_donor_ctrl_status = QtGui.QLineEdit(self.widget)
        self.lineEdit_donor_ctrl_status.setEnabled(False)
        self.lineEdit_donor_ctrl_status.setReadOnly(True)
        self.lineEdit_donor_ctrl_status.setObjectName(_fromUtf8("lineEdit_donor_ctrl_status"))
        self.verticalLayout_2.addWidget(self.lineEdit_donor_ctrl_status)
        self.pushButton_donor_ctrl_start = QtGui.QPushButton(self.widget)
        self.pushButton_donor_ctrl_start.setObjectName(_fromUtf8("pushButton_donor_ctrl_start"))
        self.verticalLayout_2.addWidget(self.pushButton_donor_ctrl_start)
        self.pushButton_donor_ctrl_stop = QtGui.QPushButton(self.widget)
        self.pushButton_donor_ctrl_stop.setObjectName(_fromUtf8("pushButton_donor_ctrl_stop"))
        self.verticalLayout_2.addWidget(self.pushButton_donor_ctrl_stop)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_reveiver_ctrl = QtGui.QLabel(self.widget)
        self.label_reveiver_ctrl.setObjectName(_fromUtf8("label_reveiver_ctrl"))
        self.verticalLayout_3.addWidget(self.label_reveiver_ctrl)
        self.lineEdit_receiver_ctrl_status = QtGui.QLineEdit(self.widget)
        self.lineEdit_receiver_ctrl_status.setEnabled(False)
        self.lineEdit_receiver_ctrl_status.setReadOnly(True)
        self.lineEdit_receiver_ctrl_status.setObjectName(_fromUtf8("lineEdit_receiver_ctrl_status"))
        self.verticalLayout_3.addWidget(self.lineEdit_receiver_ctrl_status)
        self.pushButton_receiver_ctrl_start = QtGui.QPushButton(self.widget)
        self.pushButton_receiver_ctrl_start.setObjectName(_fromUtf8("pushButton_receiver_ctrl_start"))
        self.verticalLayout_3.addWidget(self.pushButton_receiver_ctrl_start)
        self.pushButton_receiver_ctrl_stop = QtGui.QPushButton(self.widget)
        self.pushButton_receiver_ctrl_stop.setObjectName(_fromUtf8("pushButton_receiver_ctrl_stop"))
        self.verticalLayout_3.addWidget(self.pushButton_receiver_ctrl_stop)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_laser_ctrl = QtGui.QLabel(self.widget)
        self.label_laser_ctrl.setObjectName(_fromUtf8("label_laser_ctrl"))
        self.verticalLayout_4.addWidget(self.label_laser_ctrl)
        self.lineEdit_laser_ctrl_status = QtGui.QLineEdit(self.widget)
        self.lineEdit_laser_ctrl_status.setEnabled(False)
        self.lineEdit_laser_ctrl_status.setReadOnly(True)
        self.lineEdit_laser_ctrl_status.setObjectName(_fromUtf8("lineEdit_laser_ctrl_status"))
        self.verticalLayout_4.addWidget(self.lineEdit_laser_ctrl_status)
        self.pushButton_laser_ctrl_start = QtGui.QPushButton(self.widget)
        self.pushButton_laser_ctrl_start.setObjectName(_fromUtf8("pushButton_laser_ctrl_start"))
        self.verticalLayout_4.addWidget(self.pushButton_laser_ctrl_start)
        self.pushButton_laser_ctrl_stop = QtGui.QPushButton(self.widget)
        self.pushButton_laser_ctrl_stop.setObjectName(_fromUtf8("pushButton_laser_ctrl_stop"))
        self.verticalLayout_4.addWidget(self.pushButton_laser_ctrl_stop)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_general)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 230, 751, 80))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget1 = QtGui.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(30, 30, 471, 30))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_global = QtGui.QComboBox(self.widget1)
        self.comboBox_global.setObjectName(_fromUtf8("comboBox_global"))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.comboBox_global.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_global)
        self.lineEdit_global = QtGui.QLineEdit(self.widget1)
        self.lineEdit_global.setEnabled(True)
        self.lineEdit_global.setObjectName(_fromUtf8("lineEdit_global"))
        self.horizontalLayout.addWidget(self.lineEdit_global)
        self.pushButton_global = QtGui.QPushButton(self.widget1)
        self.pushButton_global.setEnabled(True)
        self.pushButton_global.setObjectName(_fromUtf8("pushButton_global"))
        self.horizontalLayout.addWidget(self.pushButton_global)
        self.tabWidget.addTab(self.tab_general, _fromUtf8(""))
        self.tab_z_stage = QtGui.QWidget()
        self.tab_z_stage.setObjectName(_fromUtf8("tab_z_stage"))
        self.groupBox_zstage = QtGui.QGroupBox(self.tab_z_stage)
        self.groupBox_zstage.setGeometry(QtCore.QRect(20, 10, 751, 121))
        self.groupBox_zstage.setObjectName(_fromUtf8("groupBox_zstage"))
        self.widget2 = QtGui.QWidget(self.groupBox_zstage)
        self.widget2.setGeometry(QtCore.QRect(22, 31, 389, 62))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lcdNumber_zstage = QtGui.QLCDNumber(self.widget2)
        self.lcdNumber_zstage.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_zstage.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_zstage.setObjectName(_fromUtf8("lcdNumber_zstage"))
        self.verticalLayout_5.addWidget(self.lcdNumber_zstage)
        self.pushButton_zstage_home = QtGui.QPushButton(self.widget2)
        self.pushButton_zstage_home.setObjectName(_fromUtf8("pushButton_zstage_home"))
        self.verticalLayout_5.addWidget(self.pushButton_zstage_home)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_zstage_move_rel = QtGui.QLineEdit(self.widget2)
        self.lineEdit_zstage_move_rel.setObjectName(_fromUtf8("lineEdit_zstage_move_rel"))
        self.verticalLayout_6.addWidget(self.lineEdit_zstage_move_rel)
        self.pushButton_zstage_move_rel = QtGui.QPushButton(self.widget2)
        self.pushButton_zstage_move_rel.setObjectName(_fromUtf8("pushButton_zstage_move_rel"))
        self.verticalLayout_6.addWidget(self.pushButton_zstage_move_rel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lineEdit_zstage_move_abs = QtGui.QLineEdit(self.widget2)
        self.lineEdit_zstage_move_abs.setObjectName(_fromUtf8("lineEdit_zstage_move_abs"))
        self.verticalLayout_7.addWidget(self.lineEdit_zstage_move_abs)
        self.pushButton_zstage_move_abs = QtGui.QPushButton(self.widget2)
        self.pushButton_zstage_move_abs.setObjectName(_fromUtf8("pushButton_zstage_move_abs"))
        self.verticalLayout_7.addWidget(self.pushButton_zstage_move_abs)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_z_stage, _fromUtf8(""))
        self.tab_donor = QtGui.QWidget()
        self.tab_donor.setObjectName(_fromUtf8("tab_donor"))
        self.groupBox_donor_x = QtGui.QGroupBox(self.tab_donor)
        self.groupBox_donor_x.setGeometry(QtCore.QRect(20, 10, 751, 161))
        self.groupBox_donor_x.setObjectName(_fromUtf8("groupBox_donor_x"))
        self.widget3 = QtGui.QWidget(self.groupBox_donor_x)
        self.widget3.setGeometry(QtCore.QRect(22, 31, 389, 62))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lcdNumber_donor_x = QtGui.QLCDNumber(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lcdNumber_donor_x.setFont(font)
        self.lcdNumber_donor_x.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_donor_x.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_donor_x.setSmallDecimalPoint(False)
        self.lcdNumber_donor_x.setNumDigits(5)
        self.lcdNumber_donor_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_donor_x.setObjectName(_fromUtf8("lcdNumber_donor_x"))
        self.verticalLayout_8.addWidget(self.lcdNumber_donor_x)
        self.pushButton_donor_x_home = QtGui.QPushButton(self.widget3)
        self.pushButton_donor_x_home.setObjectName(_fromUtf8("pushButton_donor_x_home"))
        self.verticalLayout_8.addWidget(self.pushButton_donor_x_home)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_donor_x_move_rel = QtGui.QLineEdit(self.widget3)
        self.lineEdit_donor_x_move_rel.setObjectName(_fromUtf8("lineEdit_donor_x_move_rel"))
        self.verticalLayout_9.addWidget(self.lineEdit_donor_x_move_rel)
        self.pushButton_donor_x_move_rel = QtGui.QPushButton(self.widget3)
        self.pushButton_donor_x_move_rel.setObjectName(_fromUtf8("pushButton_donor_x_move_rel"))
        self.verticalLayout_9.addWidget(self.pushButton_donor_x_move_rel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lineEdit_donor_x_move_abs = QtGui.QLineEdit(self.widget3)
        self.lineEdit_donor_x_move_abs.setObjectName(_fromUtf8("lineEdit_donor_x_move_abs"))
        self.verticalLayout_10.addWidget(self.lineEdit_donor_x_move_abs)
        self.pushButton_donor_x_move_abs = QtGui.QPushButton(self.widget3)
        self.pushButton_donor_x_move_abs.setObjectName(_fromUtf8("pushButton_donor_x_move_abs"))
        self.verticalLayout_10.addWidget(self.pushButton_donor_x_move_abs)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.groupBox_donor_y = QtGui.QGroupBox(self.tab_donor)
        self.groupBox_donor_y.setGeometry(QtCore.QRect(20, 180, 751, 161))
        self.groupBox_donor_y.setObjectName(_fromUtf8("groupBox_donor_y"))
        self.widget4 = QtGui.QWidget(self.groupBox_donor_y)
        self.widget4.setGeometry(QtCore.QRect(22, 31, 389, 62))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.lcdNumber_donor_y = QtGui.QLCDNumber(self.widget4)
        self.lcdNumber_donor_y.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_donor_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_donor_y.setObjectName(_fromUtf8("lcdNumber_donor_y"))
        self.verticalLayout_11.addWidget(self.lcdNumber_donor_y)
        self.pushButton_donor_y_home = QtGui.QPushButton(self.widget4)
        self.pushButton_donor_y_home.setObjectName(_fromUtf8("pushButton_donor_y_home"))
        self.verticalLayout_11.addWidget(self.pushButton_donor_y_home)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lineEdit_donor_y_move_rel = QtGui.QLineEdit(self.widget4)
        self.lineEdit_donor_y_move_rel.setObjectName(_fromUtf8("lineEdit_donor_y_move_rel"))
        self.verticalLayout_12.addWidget(self.lineEdit_donor_y_move_rel)
        self.pushButton_donor_y_move_rel = QtGui.QPushButton(self.widget4)
        self.pushButton_donor_y_move_rel.setObjectName(_fromUtf8("pushButton_donor_y_move_rel"))
        self.verticalLayout_12.addWidget(self.pushButton_donor_y_move_rel)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.lineEdit_donor_y_move_abs = QtGui.QLineEdit(self.widget4)
        self.lineEdit_donor_y_move_abs.setObjectName(_fromUtf8("lineEdit_donor_y_move_abs"))
        self.verticalLayout_13.addWidget(self.lineEdit_donor_y_move_abs)
        self.pushButton_donor_y_move_abs = QtGui.QPushButton(self.widget4)
        self.pushButton_donor_y_move_abs.setObjectName(_fromUtf8("pushButton_donor_y_move_abs"))
        self.verticalLayout_13.addWidget(self.pushButton_donor_y_move_abs)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab_donor, _fromUtf8(""))
        self.tab_receiver_stepper = QtGui.QWidget()
        self.tab_receiver_stepper.setObjectName(_fromUtf8("tab_receiver_stepper"))
        self.groupBox_receiver_stepper_x = QtGui.QGroupBox(self.tab_receiver_stepper)
        self.groupBox_receiver_stepper_x.setGeometry(QtCore.QRect(20, 10, 751, 161))
        self.groupBox_receiver_stepper_x.setObjectName(_fromUtf8("groupBox_receiver_stepper_x"))
        self.widget5 = QtGui.QWidget(self.groupBox_receiver_stepper_x)
        self.widget5.setGeometry(QtCore.QRect(22, 33, 389, 62))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lcdNumber_receiver_stepper_x = QtGui.QLCDNumber(self.widget5)
        self.lcdNumber_receiver_stepper_x.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_receiver_stepper_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_receiver_stepper_x.setObjectName(_fromUtf8("lcdNumber_receiver_stepper_x"))
        self.verticalLayout_14.addWidget(self.lcdNumber_receiver_stepper_x)
        self.pushButton_receiver_stepper_x_home = QtGui.QPushButton(self.widget5)
        self.pushButton_receiver_stepper_x_home.setObjectName(_fromUtf8("pushButton_receiver_stepper_x_home"))
        self.verticalLayout_14.addWidget(self.pushButton_receiver_stepper_x_home)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lineEdit_receiver_stepper_x_move_rel = QtGui.QLineEdit(self.widget5)
        self.lineEdit_receiver_stepper_x_move_rel.setObjectName(_fromUtf8("lineEdit_receiver_stepper_x_move_rel"))
        self.verticalLayout_15.addWidget(self.lineEdit_receiver_stepper_x_move_rel)
        self.pushButton_receiver_stepper_x_move_rel = QtGui.QPushButton(self.widget5)
        self.pushButton_receiver_stepper_x_move_rel.setObjectName(_fromUtf8("pushButton_receiver_stepper_x_move_rel"))
        self.verticalLayout_15.addWidget(self.pushButton_receiver_stepper_x_move_rel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.lineEdit_receiver_stepper_x_move_abs = QtGui.QLineEdit(self.widget5)
        self.lineEdit_receiver_stepper_x_move_abs.setObjectName(_fromUtf8("lineEdit_receiver_stepper_x_move_abs"))
        self.verticalLayout_16.addWidget(self.lineEdit_receiver_stepper_x_move_abs)
        self.pushButton_receiver_stepper_x_move_abs = QtGui.QPushButton(self.widget5)
        self.pushButton_receiver_stepper_x_move_abs.setObjectName(_fromUtf8("pushButton_receiver_stepper_x_move_abs"))
        self.verticalLayout_16.addWidget(self.pushButton_receiver_stepper_x_move_abs)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.groupBox_receiver_stepper_y = QtGui.QGroupBox(self.tab_receiver_stepper)
        self.groupBox_receiver_stepper_y.setGeometry(QtCore.QRect(20, 180, 751, 161))
        self.groupBox_receiver_stepper_y.setObjectName(_fromUtf8("groupBox_receiver_stepper_y"))
        self.widget6 = QtGui.QWidget(self.groupBox_receiver_stepper_y)
        self.widget6.setGeometry(QtCore.QRect(22, 31, 389, 62))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.lcdNumber_receiver_stepper_y = QtGui.QLCDNumber(self.widget6)
        self.lcdNumber_receiver_stepper_y.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_receiver_stepper_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_receiver_stepper_y.setObjectName(_fromUtf8("lcdNumber_receiver_stepper_y"))
        self.verticalLayout_17.addWidget(self.lcdNumber_receiver_stepper_y)
        self.pushButton_receiver_stepper_y_home = QtGui.QPushButton(self.widget6)
        self.pushButton_receiver_stepper_y_home.setObjectName(_fromUtf8("pushButton_receiver_stepper_y_home"))
        self.verticalLayout_17.addWidget(self.pushButton_receiver_stepper_y_home)
        self.horizontalLayout_6.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.lineEdit_receiver_stepper_y_move_rel = QtGui.QLineEdit(self.widget6)
        self.lineEdit_receiver_stepper_y_move_rel.setObjectName(_fromUtf8("lineEdit_receiver_stepper_y_move_rel"))
        self.verticalLayout_18.addWidget(self.lineEdit_receiver_stepper_y_move_rel)
        self.pushButton_receiver_stepper_y_move_rel = QtGui.QPushButton(self.widget6)
        self.pushButton_receiver_stepper_y_move_rel.setObjectName(_fromUtf8("pushButton_receiver_stepper_y_move_rel"))
        self.verticalLayout_18.addWidget(self.pushButton_receiver_stepper_y_move_rel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.lineEdit_receiver_stepper_y_move_abs = QtGui.QLineEdit(self.widget6)
        self.lineEdit_receiver_stepper_y_move_abs.setObjectName(_fromUtf8("lineEdit_receiver_stepper_y_move_abs"))
        self.verticalLayout_19.addWidget(self.lineEdit_receiver_stepper_y_move_abs)
        self.pushButton_receiver_stepper_y_move_abs = QtGui.QPushButton(self.widget6)
        self.pushButton_receiver_stepper_y_move_abs.setObjectName(_fromUtf8("pushButton_receiver_stepper_y_move_abs"))
        self.verticalLayout_19.addWidget(self.pushButton_receiver_stepper_y_move_abs)
        self.horizontalLayout_6.addLayout(self.verticalLayout_19)
        self.groupBox_receiver_stepper_z = QtGui.QGroupBox(self.tab_receiver_stepper)
        self.groupBox_receiver_stepper_z.setGeometry(QtCore.QRect(20, 350, 751, 161))
        self.groupBox_receiver_stepper_z.setObjectName(_fromUtf8("groupBox_receiver_stepper_z"))
        self.widget7 = QtGui.QWidget(self.groupBox_receiver_stepper_z)
        self.widget7.setGeometry(QtCore.QRect(22, 31, 389, 62))
        self.widget7.setObjectName(_fromUtf8("widget7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.lcdNumber_receiver_stepper_z = QtGui.QLCDNumber(self.widget7)
        self.lcdNumber_receiver_stepper_z.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_receiver_stepper_z.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_receiver_stepper_z.setObjectName(_fromUtf8("lcdNumber_receiver_stepper_z"))
        self.verticalLayout_20.addWidget(self.lcdNumber_receiver_stepper_z)
        self.pushButton_receiver_stepper_z_home = QtGui.QPushButton(self.widget7)
        self.pushButton_receiver_stepper_z_home.setObjectName(_fromUtf8("pushButton_receiver_stepper_z_home"))
        self.verticalLayout_20.addWidget(self.pushButton_receiver_stepper_z_home)
        self.horizontalLayout_7.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.lineEdit_receiver_stepper_z_move_rel = QtGui.QLineEdit(self.widget7)
        self.lineEdit_receiver_stepper_z_move_rel.setObjectName(_fromUtf8("lineEdit_receiver_stepper_z_move_rel"))
        self.verticalLayout_21.addWidget(self.lineEdit_receiver_stepper_z_move_rel)
        self.pushButton_receiver_stepper_z_move_rel = QtGui.QPushButton(self.widget7)
        self.pushButton_receiver_stepper_z_move_rel.setObjectName(_fromUtf8("pushButton_receiver_stepper_z_move_rel"))
        self.verticalLayout_21.addWidget(self.pushButton_receiver_stepper_z_move_rel)
        self.horizontalLayout_7.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.lineEdit_receiver_stepper_z_move_abs = QtGui.QLineEdit(self.widget7)
        self.lineEdit_receiver_stepper_z_move_abs.setObjectName(_fromUtf8("lineEdit_receiver_stepper_z_move_abs"))
        self.verticalLayout_22.addWidget(self.lineEdit_receiver_stepper_z_move_abs)
        self.pushButton_receiver_stepper_z_move_abs = QtGui.QPushButton(self.widget7)
        self.pushButton_receiver_stepper_z_move_abs.setObjectName(_fromUtf8("pushButton_receiver_stepper_z_move_abs"))
        self.verticalLayout_22.addWidget(self.pushButton_receiver_stepper_z_move_abs)
        self.horizontalLayout_7.addLayout(self.verticalLayout_22)
        self.tabWidget.addTab(self.tab_receiver_stepper, _fromUtf8(""))
        self.tab_laser = QtGui.QWidget()
        self.tab_laser.setObjectName(_fromUtf8("tab_laser"))
        self.groupBox_laser = QtGui.QGroupBox(self.tab_laser)
        self.groupBox_laser.setGeometry(QtCore.QRect(20, 20, 751, 161))
        self.groupBox_laser.setObjectName(_fromUtf8("groupBox_laser"))
        self.widget8 = QtGui.QWidget(self.groupBox_laser)
        self.widget8.setGeometry(QtCore.QRect(30, 20, 389, 120))
        self.widget8.setObjectName(_fromUtf8("widget8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget8)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_3 = QtGui.QLabel(self.widget8)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_23.addWidget(self.label_3)
        self.lcdNumber_laser = QtGui.QLCDNumber(self.widget8)
        self.lcdNumber_laser.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_laser.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_laser.setObjectName(_fromUtf8("lcdNumber_laser"))
        self.verticalLayout_23.addWidget(self.lcdNumber_laser)
        self.pushButton_laser_on = QtGui.QPushButton(self.widget8)
        self.pushButton_laser_on.setObjectName(_fromUtf8("pushButton_laser_on"))
        self.verticalLayout_23.addWidget(self.pushButton_laser_on)
        self.gridLayout_4.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label = QtGui.QLabel(self.widget8)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_24.addWidget(self.label)
        self.lineEdit_laser_power = QtGui.QLineEdit(self.widget8)
        self.lineEdit_laser_power.setObjectName(_fromUtf8("lineEdit_laser_power"))
        self.verticalLayout_24.addWidget(self.lineEdit_laser_power)
        self.pushButton_laser_power = QtGui.QPushButton(self.widget8)
        self.pushButton_laser_power.setObjectName(_fromUtf8("pushButton_laser_power"))
        self.verticalLayout_24.addWidget(self.pushButton_laser_power)
        self.gridLayout_4.addLayout(self.verticalLayout_24, 0, 1, 1, 1)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_2 = QtGui.QLabel(self.widget8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_25.addWidget(self.label_2)
        self.lineEdit_laser_numberPulses = QtGui.QLineEdit(self.widget8)
        self.lineEdit_laser_numberPulses.setObjectName(_fromUtf8("lineEdit_laser_numberPulses"))
        self.verticalLayout_25.addWidget(self.lineEdit_laser_numberPulses)
        self.pushButton_laser_multiPulse = QtGui.QPushButton(self.widget8)
        self.pushButton_laser_multiPulse.setObjectName(_fromUtf8("pushButton_laser_multiPulse"))
        self.verticalLayout_25.addWidget(self.pushButton_laser_multiPulse)
        self.pushButton_laser_singlePulse = QtGui.QPushButton(self.widget8)
        self.pushButton_laser_singlePulse.setObjectName(_fromUtf8("pushButton_laser_singlePulse"))
        self.verticalLayout_25.addWidget(self.pushButton_laser_singlePulse)
        self.gridLayout_4.addLayout(self.verticalLayout_25, 0, 2, 2, 1)
        self.pushButton_laser_off = QtGui.QPushButton(self.widget8)
        self.pushButton_laser_off.setObjectName(_fromUtf8("pushButton_laser_off"))
        self.gridLayout_4.addWidget(self.pushButton_laser_off, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_laser, _fromUtf8(""))
        self.tab_scripts = QtGui.QWidget()
        self.tab_scripts.setObjectName(_fromUtf8("tab_scripts"))
        self.groupBox_scripts_print3D = QtGui.QGroupBox(self.tab_scripts)
        self.groupBox_scripts_print3D.setGeometry(QtCore.QRect(30, 20, 741, 80))
        self.groupBox_scripts_print3D.setObjectName(_fromUtf8("groupBox_scripts_print3D"))
        self.label_4 = QtGui.QLabel(self.groupBox_scripts_print3D)
        self.label_4.setGeometry(QtCore.QRect(140, 22, 96, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_18 = QtGui.QLabel(self.groupBox_scripts_print3D)
        self.label_18.setGeometry(QtCore.QRect(290, 22, 95, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.widget9 = QtGui.QWidget(self.groupBox_scripts_print3D)
        self.widget9.setGeometry(QtCore.QRect(21, 40, 510, 30))
        self.widget9.setObjectName(_fromUtf8("widget9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget9)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_super_print3D = QtGui.QPushButton(self.widget9)
        self.pushButton_super_print3D.setObjectName(_fromUtf8("pushButton_super_print3D"))
        self.horizontalLayout_8.addWidget(self.pushButton_super_print3D)
        self.lineEdit_super_print3D_laserPower = QtGui.QLineEdit(self.widget9)
        self.lineEdit_super_print3D_laserPower.setObjectName(_fromUtf8("lineEdit_super_print3D_laserPower"))
        self.horizontalLayout_8.addWidget(self.lineEdit_super_print3D_laserPower)
        self.lineEdit_super_print3D_laserPower_2 = QtGui.QLineEdit(self.widget9)
        self.lineEdit_super_print3D_laserPower_2.setObjectName(_fromUtf8("lineEdit_super_print3D_laserPower_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_super_print3D_laserPower_2)
        self.checkBox_super_print3D = QtGui.QCheckBox(self.widget9)
        self.checkBox_super_print3D.setObjectName(_fromUtf8("checkBox_super_print3D"))
        self.horizontalLayout_8.addWidget(self.checkBox_super_print3D)
        self.groupBox_scripts_print3D_2 = QtGui.QGroupBox(self.tab_scripts)
        self.groupBox_scripts_print3D_2.setGeometry(QtCore.QRect(30, 110, 741, 131))
        self.groupBox_scripts_print3D_2.setObjectName(_fromUtf8("groupBox_scripts_print3D_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_scripts_print3D_2)
        self.label_5.setGeometry(QtCore.QRect(130, 22, 110, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_scripts_print3D_2)
        self.label_6.setGeometry(QtCore.QRect(270, 22, 114, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_scripts_print3D_2)
        self.label_7.setGeometry(QtCore.QRect(415, 22, 123, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_12 = QtGui.QLabel(self.groupBox_scripts_print3D_2)
        self.label_12.setGeometry(QtCore.QRect(123, 76, 110, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_scripts_print3D_2)
        self.label_13.setGeometry(QtCore.QRect(269, 76, 126, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.widget10 = QtGui.QWidget(self.groupBox_scripts_print3D_2)
        self.widget10.setGeometry(QtCore.QRect(22, 40, 527, 30))
        self.widget10.setObjectName(_fromUtf8("widget10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget10)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_super_energy = QtGui.QPushButton(self.widget10)
        self.pushButton_super_energy.setObjectName(_fromUtf8("pushButton_super_energy"))
        self.horizontalLayout_9.addWidget(self.pushButton_super_energy)
        self.lineEdit_super_energy_laser_min = QtGui.QLineEdit(self.widget10)
        self.lineEdit_super_energy_laser_min.setObjectName(_fromUtf8("lineEdit_super_energy_laser_min"))
        self.horizontalLayout_9.addWidget(self.lineEdit_super_energy_laser_min)
        self.lineEdit_super_energy_laser_max = QtGui.QLineEdit(self.widget10)
        self.lineEdit_super_energy_laser_max.setObjectName(_fromUtf8("lineEdit_super_energy_laser_max"))
        self.horizontalLayout_9.addWidget(self.lineEdit_super_energy_laser_max)
        self.lineEdit_super_energy_laser_delta = QtGui.QLineEdit(self.widget10)
        self.lineEdit_super_energy_laser_delta.setObjectName(_fromUtf8("lineEdit_super_energy_laser_delta"))
        self.horizontalLayout_9.addWidget(self.lineEdit_super_energy_laser_delta)
        self.widget11 = QtGui.QWidget(self.groupBox_scripts_print3D_2)
        self.widget11.setGeometry(QtCore.QRect(123, 99, 283, 24))
        self.widget11.setObjectName(_fromUtf8("widget11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget11)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineEdit_super_energy_number = QtGui.QLineEdit(self.widget11)
        self.lineEdit_super_energy_number.setObjectName(_fromUtf8("lineEdit_super_energy_number"))
        self.horizontalLayout_10.addWidget(self.lineEdit_super_energy_number)
        self.lineEdit_super_energy_spatial = QtGui.QLineEdit(self.widget11)
        self.lineEdit_super_energy_spatial.setObjectName(_fromUtf8("lineEdit_super_energy_spatial"))
        self.horizontalLayout_10.addWidget(self.lineEdit_super_energy_spatial)
        self.groupBox_scripts_print3D_3 = QtGui.QGroupBox(self.tab_scripts)
        self.groupBox_scripts_print3D_3.setGeometry(QtCore.QRect(30, 250, 741, 131))
        self.groupBox_scripts_print3D_3.setObjectName(_fromUtf8("groupBox_scripts_print3D_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_8.setGeometry(QtCore.QRect(122, 22, 78, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_9.setGeometry(QtCore.QRect(268, 22, 82, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_10.setGeometry(QtCore.QRect(414, 22, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_11.setGeometry(QtCore.QRect(414, 76, 84, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_14 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_14.setGeometry(QtCore.QRect(268, 76, 126, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_scripts_print3D_3)
        self.label_15.setGeometry(QtCore.QRect(122, 76, 110, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.widget12 = QtGui.QWidget(self.groupBox_scripts_print3D_3)
        self.widget12.setGeometry(QtCore.QRect(21, 40, 527, 30))
        self.widget12.setObjectName(_fromUtf8("widget12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget12)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pushButton_super_focus = QtGui.QPushButton(self.widget12)
        self.pushButton_super_focus.setObjectName(_fromUtf8("pushButton_super_focus"))
        self.horizontalLayout_11.addWidget(self.pushButton_super_focus)
        self.lineEdit_super_focus_z_min = QtGui.QLineEdit(self.widget12)
        self.lineEdit_super_focus_z_min.setObjectName(_fromUtf8("lineEdit_super_focus_z_min"))
        self.horizontalLayout_11.addWidget(self.lineEdit_super_focus_z_min)
        self.lineEdit_super_focus_z_max = QtGui.QLineEdit(self.widget12)
        self.lineEdit_super_focus_z_max.setObjectName(_fromUtf8("lineEdit_super_focus_z_max"))
        self.horizontalLayout_11.addWidget(self.lineEdit_super_focus_z_max)
        self.lineEdit_super_focus_z_delta = QtGui.QLineEdit(self.widget12)
        self.lineEdit_super_focus_z_delta.setObjectName(_fromUtf8("lineEdit_super_focus_z_delta"))
        self.horizontalLayout_11.addWidget(self.lineEdit_super_focus_z_delta)
        self.widget13 = QtGui.QWidget(self.groupBox_scripts_print3D_3)
        self.widget13.setGeometry(QtCore.QRect(122, 99, 427, 24))
        self.widget13.setObjectName(_fromUtf8("widget13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget13)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lineEdit_super_focus_number = QtGui.QLineEdit(self.widget13)
        self.lineEdit_super_focus_number.setObjectName(_fromUtf8("lineEdit_super_focus_number"))
        self.horizontalLayout_12.addWidget(self.lineEdit_super_focus_number)
        self.lineEdit_super_focus_spatial = QtGui.QLineEdit(self.widget13)
        self.lineEdit_super_focus_spatial.setObjectName(_fromUtf8("lineEdit_super_focus_spatial"))
        self.horizontalLayout_12.addWidget(self.lineEdit_super_focus_spatial)
        self.lineEdit_super_focus_power = QtGui.QLineEdit(self.widget13)
        self.lineEdit_super_focus_power.setObjectName(_fromUtf8("lineEdit_super_focus_power"))
        self.horizontalLayout_12.addWidget(self.lineEdit_super_focus_power)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_scripts)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 400, 541, 101))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pushButton_super_stop = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_super_stop.setGeometry(QtCore.QRect(290, 30, 211, 51))
        self.pushButton_super_stop.setObjectName(_fromUtf8("pushButton_super_stop"))
        self.pushButton_super_pause = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_super_pause.setGeometry(QtCore.QRect(40, 30, 211, 51))
        self.pushButton_super_pause.setObjectName(_fromUtf8("pushButton_super_pause"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_scripts)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 400, 181, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.widget14 = QtGui.QWidget(self.groupBox_4)
        self.widget14.setGeometry(QtCore.QRect(30, 30, 81, 53))
        self.widget14.setObjectName(_fromUtf8("widget14"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget14)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_super_perc = QtGui.QLineEdit(self.widget14)
        self.lineEdit_super_perc.setEnabled(False)
        self.lineEdit_super_perc.setObjectName(_fromUtf8("lineEdit_super_perc"))
        self.gridLayout_3.addWidget(self.lineEdit_super_perc, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget14)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 1, 1, 1)
        self.lineEdit_super_time = QtGui.QLineEdit(self.widget14)
        self.lineEdit_super_time.setEnabled(False)
        self.lineEdit_super_time.setObjectName(_fromUtf8("lineEdit_super_time"))
        self.gridLayout_3.addWidget(self.lineEdit_super_time, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget14)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_scripts, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "CONTROLLER", None))
        self.label_zstage_ctrl.setText(_translate("MainWindow", "Z_STAGE_CTRL", None))
        self.pushButton_zstage_ctrl_start.setText(_translate("MainWindow", "START", None))
        self.pushButton_zstage_ctrl_stop.setText(_translate("MainWindow", "STOP", None))
        self.label_donor_ctrl.setText(_translate("MainWindow", "DONOR_CTRL", None))
        self.pushButton_donor_ctrl_start.setText(_translate("MainWindow", "START", None))
        self.pushButton_donor_ctrl_stop.setText(_translate("MainWindow", "STOP", None))
        self.label_reveiver_ctrl.setText(_translate("MainWindow", "RECEIVER_CTRL", None))
        self.pushButton_receiver_ctrl_start.setText(_translate("MainWindow", "START", None))
        self.pushButton_receiver_ctrl_stop.setText(_translate("MainWindow", "STOP", None))
        self.label_laser_ctrl.setText(_translate("MainWindow", "LASER_CTRL", None))
        self.pushButton_laser_ctrl_start.setText(_translate("MainWindow", "START", None))
        self.pushButton_laser_ctrl_stop.setText(_translate("MainWindow", "STOP", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "GLOBAL PARAMETER", None))
        self.comboBox_global.setItemText(0, _translate("MainWindow", "gbl_receiver_x_pos", None))
        self.comboBox_global.setItemText(1, _translate("MainWindow", "gbl_receiver_y_pos", None))
        self.comboBox_global.setItemText(2, _translate("MainWindow", "gbl_receiver_z_pos", None))
        self.comboBox_global.setItemText(3, _translate("MainWindow", "gbl_donor_x_pos", None))
        self.comboBox_global.setItemText(4, _translate("MainWindow", "gbl_donor_y_pos", None))
        self.comboBox_global.setItemText(5, _translate("MainWindow", "gbl_zstage_pos", None))
        self.comboBox_global.setItemText(6, _translate("MainWindow", "gbl_laser_power", None))
        self.comboBox_global.setItemText(7, _translate("MainWindow", "gbl_receiver_x_lim_down", None))
        self.comboBox_global.setItemText(8, _translate("MainWindow", "gbl_receiver_x_lim_up", None))
        self.comboBox_global.setItemText(9, _translate("MainWindow", "gbl_receiver_y_lim_down", None))
        self.comboBox_global.setItemText(10, _translate("MainWindow", "gbl_receiver_y_lim_up", None))
        self.comboBox_global.setItemText(11, _translate("MainWindow", "gbl_receiver_z_lim_down", None))
        self.comboBox_global.setItemText(12, _translate("MainWindow", "gbl_receiver_z_lim_up", None))
        self.comboBox_global.setItemText(13, _translate("MainWindow", "gbl_donor_x_lim_down", None))
        self.comboBox_global.setItemText(14, _translate("MainWindow", "gbl_donor_x_lim_up", None))
        self.comboBox_global.setItemText(15, _translate("MainWindow", "gbl_donor_y_lim_down", None))
        self.comboBox_global.setItemText(16, _translate("MainWindow", "gbl_donor_y_lim_up", None))
        self.comboBox_global.setItemText(17, _translate("MainWindow", "gbl_zstage_lim_down", None))
        self.comboBox_global.setItemText(18, _translate("MainWindow", "gbl_zstage_lim_up", None))
        self.comboBox_global.setItemText(19, _translate("MainWindow", "gbl_laser_power_lim_down", None))
        self.comboBox_global.setItemText(20, _translate("MainWindow", "gbl_laser_power_lim_up", None))
        self.comboBox_global.setItemText(21, _translate("MainWindow", "gbl_donor_x_refresh_bound_A_up", None))
        self.comboBox_global.setItemText(22, _translate("MainWindow", "gbl_donor_x_refresh_bound_A_down", None))
        self.comboBox_global.setItemText(23, _translate("MainWindow", "gbl_donor_y_refresh_bound_A_up", None))
        self.comboBox_global.setItemText(24, _translate("MainWindow", "gbl_donor_y_refresh_bound_A_down", None))
        self.comboBox_global.setItemText(25, _translate("MainWindow", "gbl_donor_x_refresh_bound_B_up", None))
        self.comboBox_global.setItemText(26, _translate("MainWindow", "gbl_donor_x_refresh_bound_B_down", None))
        self.comboBox_global.setItemText(27, _translate("MainWindow", "gbl_donor_y_refresh_bound_B_up", None))
        self.comboBox_global.setItemText(28, _translate("MainWindow", "gbl_donor_y_refresh_bound_B_down", None))
        self.comboBox_global.setItemText(29, _translate("MainWindow", "gbl_donor_refresh_distance", None))
        self.comboBox_global.setItemText(30, _translate("MainWindow", "gbl_super_pause", None))
        self.comboBox_global.setItemText(31, _translate("MainWindow", "gbl_super_stop", None))
        self.comboBox_global.setItemText(32, _translate("MainWindow", "gbl_super_settling_delay", None))
        self.pushButton_global.setText(_translate("MainWindow", "SET NEW VALUE", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("MainWindow", "|  GENERAL  |", None))
        self.groupBox_zstage.setTitle(_translate("MainWindow", "Z STAGE", None))
        self.pushButton_zstage_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_zstage_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_zstage_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_z_stage), _translate("MainWindow", "|  Z_STAGE  |", None))
        self.groupBox_donor_x.setTitle(_translate("MainWindow", "DONOR X", None))
        self.pushButton_donor_x_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_donor_x_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_donor_x_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.groupBox_donor_y.setTitle(_translate("MainWindow", "DONOR Y", None))
        self.pushButton_donor_y_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_donor_y_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_donor_y_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_donor), _translate("MainWindow", "|  DONOR  |", None))
        self.groupBox_receiver_stepper_x.setTitle(_translate("MainWindow", "RECEIVER X", None))
        self.pushButton_receiver_stepper_x_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_receiver_stepper_x_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_receiver_stepper_x_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.groupBox_receiver_stepper_y.setTitle(_translate("MainWindow", "RECEIVER Y", None))
        self.pushButton_receiver_stepper_y_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_receiver_stepper_y_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_receiver_stepper_y_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.groupBox_receiver_stepper_z.setTitle(_translate("MainWindow", "RECEIVER Z", None))
        self.pushButton_receiver_stepper_z_home.setText(_translate("MainWindow", "HOME", None))
        self.pushButton_receiver_stepper_z_move_rel.setText(_translate("MainWindow", "MOVE_REL [mm]", None))
        self.pushButton_receiver_stepper_z_move_abs.setText(_translate("MainWindow", "MOVE_ABS [mm]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_receiver_stepper), _translate("MainWindow", "|  RECEIVER  |", None))
        self.groupBox_laser.setTitle(_translate("MainWindow", "LASER", None))
        self.label_3.setText(_translate("MainWindow", "POWER", None))
        self.pushButton_laser_on.setText(_translate("MainWindow", "LASER ON", None))
        self.label.setText(_translate("MainWindow", "POWER SETPOINT", None))
        self.pushButton_laser_power.setText(_translate("MainWindow", "SET POWER [%]", None))
        self.label_2.setText(_translate("MainWindow", "NUMBER OF PULSES", None))
        self.pushButton_laser_multiPulse.setText(_translate("MainWindow", "MULTI PULSE [#]", None))
        self.pushButton_laser_singlePulse.setText(_translate("MainWindow", "SINGLE PULSE", None))
        self.pushButton_laser_off.setText(_translate("MainWindow", "LASER OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_laser), _translate("MainWindow", "| LASER |", None))
        self.groupBox_scripts_print3D.setTitle(_translate("MainWindow", "PRINT 3D", None))
        self.label_4.setText(_translate("MainWindow", "LASER POWER A", None))
        self.label_18.setText(_translate("MainWindow", "LASER POWER B", None))
        self.pushButton_super_print3D.setText(_translate("MainWindow", "START", None))
        self.lineEdit_super_print3D_laserPower.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_super_print3D_laserPower_2.setText(_translate("MainWindow", "0.0", None))
        self.checkBox_super_print3D.setText(_translate("MainWindow", "MULTIMATERIAL", None))
        self.groupBox_scripts_print3D_2.setTitle(_translate("MainWindow", "ENERGY SCAN", None))
        self.label_5.setText(_translate("MainWindow", "LASER POWER MIN", None))
        self.label_6.setText(_translate("MainWindow", "LASER POWER MAX", None))
        self.label_7.setText(_translate("MainWindow", "LASER POWER DELTA", None))
        self.label_12.setText(_translate("MainWindow", "NUMBER OF STEPS", None))
        self.label_13.setText(_translate("MainWindow", "SPATIAL SEPARATION", None))
        self.pushButton_super_energy.setText(_translate("MainWindow", "START", None))
        self.lineEdit_super_energy_laser_min.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_super_energy_laser_max.setText(_translate("MainWindow", "100.0", None))
        self.lineEdit_super_energy_laser_delta.setText(_translate("MainWindow", "10.0", None))
        self.lineEdit_super_energy_number.setText(_translate("MainWindow", "10", None))
        self.lineEdit_super_energy_spatial.setText(_translate("MainWindow", "0.05", None))
        self.groupBox_scripts_print3D_3.setTitle(_translate("MainWindow", "FOCUS SCAN", None))
        self.label_8.setText(_translate("MainWindow", "Z_STAGE MIN", None))
        self.label_9.setText(_translate("MainWindow", "Z_STAGE MAX", None))
        self.label_10.setText(_translate("MainWindow", "Z_STAGE DELTA", None))
        self.label_11.setText(_translate("MainWindow", "LASER POWER", None))
        self.label_14.setText(_translate("MainWindow", "SPATIAL SEPARATION", None))
        self.label_15.setText(_translate("MainWindow", "NUMBER OF STEPS", None))
        self.pushButton_super_focus.setText(_translate("MainWindow", "START", None))
        self.lineEdit_super_focus_z_min.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_super_focus_z_max.setText(_translate("MainWindow", "10.0", None))
        self.lineEdit_super_focus_z_delta.setText(_translate("MainWindow", "1.0", None))
        self.lineEdit_super_focus_number.setText(_translate("MainWindow", "10", None))
        self.lineEdit_super_focus_spatial.setText(_translate("MainWindow", "0.05", None))
        self.lineEdit_super_focus_power.setText(_translate("MainWindow", "20.0", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "SCRIPT CONTROL", None))
        self.pushButton_super_stop.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_super_pause.setText(_translate("MainWindow", "PAUSE", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "PROGRESS", None))
        self.lineEdit_super_perc.setText(_translate("MainWindow", "0.0", None))
        self.label_16.setText(_translate("MainWindow", "[%]", None))
        self.lineEdit_super_time.setText(_translate("MainWindow", "0.0", None))
        self.label_17.setText(_translate("MainWindow", "[min]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scripts), _translate("MainWindow", "| SCRIPTS |", None))

